words = ("alligator", "ant", "anteater", "ape"
 , "bat", "bear", "beaver", "bee", "bison", "boar", "buffalo",
 "butterfly", "camel", "capybara",  "cat", "caterpillar",
 "cheetah", "chicken", "chimpanzee", "clam", "cobra", "cockroach",
 "crab", "crane", "crocodile", "crow","deer", "dinosaur",
 "dog", "dogfish", "dolphin", "donkey", "dove", "dragonfly",
 "duck", "dugong", "dunlin", "eagle", "echidna", "eel", "eland", "elephant",  "elk", "emu",
 "falcon", "ferret", "finch", "fish", "flamingo", "fly", "fox", "frog",
 "gerbil", "giraffe", "gnat", "gnu", "goat", "goldfinch", "goldfish", "goose", "gorilla",
  "grasshopper", "hamster", "hare", "hawk",
 "hedgehog", "heron", "herring", "hippopotamus", "hornet", "horse", "human", "hummingbird",
 "hyena","jackal", "jaguar", "jellyfish", "kangaroo", "kingfisher",
 "koala", "leopard", "lion",
 "llama", "lobster","mantis", "mongoose",
 "monkey", "moose", "mosquito", "mouse","nightingale",
 "octopus", "ostrich", "otter", "owl", "ox", "oyster",
 "panda", "panther", "parrot","penguin","pig", "pigeon", "polar-bear", "pony", "porcupine", "porpoise", "quail", "quelea",
 "rabbit", "raccoon", "rat", "raven", "red-deer", "red-panda",
 "reindeer", "rhinoceros", "salamander", "salmon",
   "scorpion", "seahorse", "seal", "shark", "sheep", "snail",
 "snake", "sparrow", "spider","squid", "squirrel","stingray",
 "swallow", "swan", "termite", "tiger", "toad", "turkey",
 "turtle", "viper", "vulture", "walrus", "weasel", "whale", "wildcat",
 "wolf", "wolverine", "woodcock", "woodpecker", "worm", "yak", "zebra",
 "apple", "banana", "orange", "strawberry", "grape", "mango", "pineapple", "watermelon", 
"peach", "cherry", "blueberry", "raspberry", "blackberry", "kiwi", "pear", "plum", 
"pomegranate", "avocado", "lemon", "lime", "grapefruit", "fig", "date", "papaya", 
"guava", "lychee", "dragonfruit", "passionfruit", "melon", "cranberry", "apricot", "coconut",
"carrot", "broccoli", "spinach", "potato", "tomato", "cucumber", "lettuce", "onion", 
"garlic", "ginger", "bell pepper", "zucchini", "eggplant", "cabbage", "cauliflower", 
"asparagus", "celery", "radish", "turnip", "beetroot", "sweet potato", "pumpkin", "squash", 
"mushroom", "peas", "green beans", "okra", "corn", "happy", "sad", "angry", "laugh", "cry", "giggle",
"chuckle", "dance", "sing", "hug", "kiss", "paint", "see", "sea", "give", "take", "snatch", "play",
"throw", "kick", "slap")
