words = ("alligator", "ant", "anteater", "ape"
 , "bat", "bear", "beaver", "bee", "bison", "boar", "buffalo",
 "butterfly", "camel", "capybara",  "cat", "caterpillar",
 "cheetah", "chicken", "chimpanzee", "clam", "cobra", "cockroach",
 "crab", "crane", "crocodile", "crow","deer", "dinosaur",
 "dog", "dogfish", "dolphin", "donkey", "dove", "dragonfly",
 "duck", "dugong", "dunlin", "eagle", "echidna", "eel", "eland", "elephant",  "elk", "emu",
 "falcon", "ferret", "finch", "fish", "flamingo", "fly", "fox", "frog",
 "gerbil", "giraffe", "gnat", "gnu", "goat", "goldfinch", "goldfish", "goose", "gorilla",
  "grasshopper", "hamster", "hare", "hawk",
 "hedgehog", "heron", "herring", "hippopotamus", "hornet", "horse", "human", "hummingbird",
 "hyena","jackal", "jaguar", "jellyfish", "kangaroo", "kingfisher",
 "koala", "leopard", "lion",
 "llama", "lobster","mantis", "mongoose",
 "monkey", "moose", "mosquito", "mouse","nightingale",
 "octopus", "ostrich", "otter", "owl", "ox", "oyster",
 "panda", "panther", "parrot","penguin","pig", "pigeon", "polar-bear", "pony", "porcupine", "porpoise", "quail", "quelea",
 "rabbit", "raccoon", "rat", "raven", "red-deer", "red-panda",
 "reindeer", "rhinoceros", "salamander", "salmon",
   "scorpion", "seahorse", "seal", "shark", "sheep", "snail",
 "snake", "sparrow", "spider","squid", "squirrel","stingray",
 "swallow", "swan", "termite", "tiger", "toad", "turkey",
 "turtle", "viper", "vulture", "walrus", "weasel", "whale", "wildcat",
 "wolf", "wolverine", "woodcock", "woodpecker", "worm", "yak", "zebra",
 "Apple", "Banana", "Orange", "Strawberry", "Grape", "Mango", "Pineapple", "Watermelon", 
"Peach", "Cherry", "Blueberry", "Raspberry", "Blackberry", "Kiwi", "Pear", "Plum", 
"Pomegranate", "Avocado", "Lemon", "Lime", "Grapefruit", "Fig", "Date", "Papaya", 
"Guava", "Lychee", "Dragonfruit", "Passionfruit", "Melon", "Cranberry", "Apricot", "Coconut",
"Carrot", "Broccoli", "Spinach", "Potato", "Tomato", "Cucumber", "Lettuce", "Onion", 
"Garlic", "Ginger", "Bell Pepper", "Zucchini", "Eggplant", "Cabbage", "Cauliflower", "Kale", 
"Asparagus", "Celery", "Radish", "Turnip", "Beetroot", "Sweet Potato", "Pumpkin", "Squash", 
"Mushroom", "Peas", "Green Beans", "Okra", "Corn", "Leek", "Artichoke", "Brussels Sprout")
